services:
  mysql:
    image: mysql
    container_name: mysql-pi
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pi
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql:/var/lib/mysql
